dataset1:
	wget https://github.com/BiodataAnalysisGroup/UMIc/blob/master/data/case1/case1_R1.fastq.gz
	wget https://github.com/BiodataAnalysisGroup/UMIc/blob/master/data/case1/case1_R2.fastq.gz
	mv case1_R1.fastq.gz dataset1_R1.fastq.gz
	mv case1_R2.fastq.gz dataset1_R2.fastq.gz


dataset2:
	wget https://github.com/BiodataAnalysisGroup/UMIc/blob/master/data/case2/case2_R1_1.fastq.gz
	wget https://github.com/BiodataAnalysisGroup/UMIc/blob/master/data/case2/case2_R2_1.fastq.gz
	mv case2_R1_1.fastq.gz dataset2_R1.fastq.gz
	mv case2_R2_1.fastq.gz dataset2_R2.fastq.gz


dataset3:
	wget https://github.com/BiodataAnalysisGroup/UMIc/blob/master/data/case3/case3_R1.fastq.gz
	mv case3_R1.fastq.gz dataset3_R1.fastq.gz

dataset4:
	wget https://github.com/CGATOxford/UMI-tools/releases/download/v0.2.3/example.fastq.gz
	mv example.fastq.gz dataset4_R1.fastq.gz

datasets_all: dataset1 dataset2 dataset3 dataset4
	